/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pp2le;

/**
 *
 * @author Anjulie
 */

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.FileNotFoundException;

public class SearchPatientFrame extends javax.swing.JFrame {
    
    private SearchPatientFrame parent;
    private String selectedCollege = "ALL";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchPatientFrame.class.getName());

    /**
     * Creates new form SearchPatientFrame
     */
    public SearchPatientFrame() {
        initComponents();
        refreshTable();
    }
    
    public SearchPatientFrame(String college) {
        initComponents();
        this.selectedCollege = college;
        refreshTable();
    }
    
    public void refreshTable() {

        ArrayList<StudentPatient> x;

    if (selectedCollege.equals("ALL")) {
        x = MainMenuFrame.PObj.getPatientList();
    } else {
        x = MainMenuFrame.PObj.filterCollege(selectedCollege);
    }

    String[] columns = {
        "First Name",
        "Last Name",
        "ID",
        "College"
    };

    Object[][] data = new Object[x.size()][4];

    for (int i = 0; i < x.size(); i++) {
        data[i][0] = x.get(i).getFirstName();
        data[i][1] = x.get(i).getLastName();
        data[i][2] = x.get(i).getStudentID();
        data[i][3] = x.get(i).getCollege();
    }

    jTable1.setModel(new DefaultTableModel(data, columns));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Search");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Firstname", "Lastname", "ID", "College"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Delete");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        int row = jTable1.getSelectedRow();

        String id = jTable1.getValueAt(row, 2).toString();

        ArrayList<StudentPatient> list = MainMenuFrame.PObj.getPatientList();

        StudentPatient p = null;

        for (int i = 0; i < list.size(); i++) {
        if (list.get(i).getStudentID().equals(id)) {
        p = list.get(i);
        break;
        }
    }

        if (p != null) {
        PatientFormFrame PF = new PatientFormFrame(p, this);
        PF.setVisible(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int row = jTable1.getSelectedRow();

        if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a patient to delete.");
        return;
    }

        String id = jTable1.getValueAt(row, 2).toString();

        ArrayList<StudentPatient> list = MainMenuFrame.PObj.getPatientList();

        for (int i = 0; i < list.size(); i++) {
        if (list.get(i).getStudentID().equals(id)) {
            list.remove(i);
            
        try {
            MainMenuFrame.PObj.writeToFile();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        
        refreshTable();
  
            break;
        }
    }

        JOptionPane.showMessageDialog(this, "Patient deleted successfully.");

        refreshTable();
    
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String keyword = jTextField1.getText().toLowerCase();
        String columns[] = {"First Name", "Last Name", "ID", "College"};

        ArrayList<StudentPatient> baseList;

        if (selectedCollege.equals("ALL")) {
            baseList = MainMenuFrame.PObj.getPatientList();
        } else {
            baseList = MainMenuFrame.PObj.filterCollege(selectedCollege);
        }

        ArrayList<StudentPatient> result = new ArrayList<>();

        for (StudentPatient p : baseList) {
            if (keyword.isEmpty() ||
                p.getFirstName().toLowerCase().contains(keyword) ||
                p.getLastName().toLowerCase().contains(keyword) ||
                p.getStudentID().toLowerCase().contains(keyword)) {

                result.add(p);
            }
        }
        
        Object[][] data = new Object[result.size()][4];

        for (int i = 0; i < result.size(); i++) {
            data[i][0] = result.get(i).getFirstName();
            data[i][1] = result.get(i).getLastName();
            data[i][2] = result.get(i).getStudentID();
            data[i][3] = result.get(i).getCollege();
        }

        jTable1.setModel(new DefaultTableModel(data, columns));

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SearchPatientFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
